/** Reserved handles — must stay in sync with `is_reserved_username` in Postgres. */
export const RESERVED_USERNAMES = new Set([
  'admin',
  'api',
  'www',
  'tomora',
  'support',
  'help',
  'login',
  'settings',
  'u',
  'claim',
  'invite',
  'welcome',
  'profile',
  'memorial',
  'memory',
  'memories',
  'family-tree',
  'companion',
  'occasions',
  'notifications',
  'auth',
  'root',
  'null',
  'undefined',
  'about',
  'privacy',
  'terms',
  'billing',
  'delete',
  'signup',
  'signin',
  'register',
  'account',
  'accounts',
  'node',
  'nodes',
  'tree',
  'trees',
  'public',
  'private',
  'share',
  'home',
  'index',
  'app',
]);

export function isReservedUsername(username: string): boolean {
  return RESERVED_USERNAMES.has(username.toLowerCase());
}
